# Default values for note-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2
image:
  repository: "hemanthreddy739.azurecr.io/note-app"
  pullPolicy: IfNotPresent
  # override image.tag separately if needed
  tag: "sha-7348f65"
service:
  type: ClusterIP
  port: 80
resources: {}
#  limits:
#    cpu: 100m
#    memory: 128Mi
#  requests:
#    cpu: 100m
#    memory: 128Mi

nodeSelector: {}
tolerations: []
affinity: {}
